// src/html-generator.ts — self-contained HTML changelog generator for changeloom
//
// Exports generateHtml(sections, version) which returns a complete <!DOCTYPE html>
// page with dark styling, suitable for GitHub Pages hosting.

export interface CommitEntry {
  type: string;
  scope: string | null;
  subject: string;
  hash: string;
  body: string | null;
  breaking: boolean;
}

export interface SectionEntry {
  type: string;
  label: string;
  commits: CommitEntry[];
}

function escape(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * Generate a self-contained dark-themed HTML changelog page.
 *
 * @param sections - Grouped commits by type, each with a label
 * @param version  - Version string to display (e.g. "1.2.3")
 * @returns Complete <!DOCTYPE html> string with inline CSS
 */
export function generateHtml(sections: SectionEntry[], version: string): string {
  const title = `Changelog — v${escape(version)}`;

  const sectionHtml = sections
    .filter((s) => s.commits.length > 0)
    .map((s) => {
      const items = s.commits
        .map((c) => {
          const scope = c.scope ? `<span class="scope">(${escape(c.scope)})</span> ` : "";
          const shortHash = c.hash.slice(0, 7);
          const breakingBadge = c.breaking
            ? `<span class="breaking">BREAKING</span> `
            : "";
          return `        <li>${breakingBadge}${scope}${escape(c.subject)} <span class="hash">${escape(shortHash)}</span></li>`;
        })
        .join("\n");
      return `    <section>
      <h2>${escape(s.label)}</h2>
      <ul>
${items}
      </ul>
    </section>`;
    })
    .join("\n\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      background: #0d1117;
      color: #e6edf3;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif;
      font-size: 16px;
      line-height: 1.6;
      padding: 2rem 1rem;
    }

    .container {
      max-width: 800px;
      margin: 0 auto;
    }

    header {
      border-bottom: 1px solid #21262d;
      padding-bottom: 1.5rem;
      margin-bottom: 2rem;
    }

    header h1 {
      font-size: 2rem;
      font-weight: 700;
      color: #f0f6fc;
      letter-spacing: -0.02em;
    }

    header .version-badge {
      display: inline-block;
      margin-top: 0.5rem;
      background: #1f6feb;
      color: #fff;
      font-size: 0.8rem;
      font-weight: 600;
      padding: 0.2em 0.7em;
      border-radius: 999px;
    }

    section {
      margin-bottom: 2rem;
    }

    section h2 {
      font-size: 1.15rem;
      font-weight: 600;
      color: #79c0ff;
      text-transform: uppercase;
      letter-spacing: 0.06em;
      margin-bottom: 0.75rem;
      padding-bottom: 0.4rem;
      border-bottom: 1px solid #21262d;
    }

    ul {
      list-style: none;
      padding: 0;
    }

    li {
      padding: 0.4rem 0;
      border-bottom: 1px solid #161b22;
      color: #c9d1d9;
      font-size: 0.95rem;
    }

    li:last-child {
      border-bottom: none;
    }

    .scope {
      color: #d2a8ff;
      font-weight: 600;
    }

    .hash {
      font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace;
      font-size: 0.8em;
      color: #8b949e;
      background: #161b22;
      padding: 0.1em 0.4em;
      border-radius: 4px;
    }

    .breaking {
      background: #da3633;
      color: #fff;
      font-size: 0.7em;
      font-weight: 700;
      padding: 0.1em 0.5em;
      border-radius: 4px;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      vertical-align: middle;
      margin-right: 0.3em;
    }

    footer {
      margin-top: 3rem;
      padding-top: 1rem;
      border-top: 1px solid #21262d;
      text-align: center;
      font-size: 0.8rem;
      color: #484f58;
    }

    footer a {
      color: #58a6ff;
      text-decoration: none;
    }

    footer a:hover {
      text-decoration: underline;
    }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>Changelog</h1>
      <span class="version-badge">v${escape(version)}</span>
    </header>

    <main>
${sectionHtml}
    </main>

    <footer>
      Generated by changeloom
    </footer>
  </div>
</body>
</html>`;
}
